package com.oyms.model;

public class AuditStatu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditstatus.id
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditstatus.audit_statu
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    private String auditStatu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditstatus.id
     *
     * @return the value of auditstatus.id
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditstatus.id
     *
     * @param id the value for auditstatus.id
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditstatus.audit_statu
     *
     * @return the value of auditstatus.audit_statu
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    public String getAuditStatu() {
        return auditStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditstatus.audit_statu
     *
     * @param auditStatu the value for auditstatus.audit_statu
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    public void setAuditStatu(String auditStatu) {
        this.auditStatu = auditStatu == null ? null : auditStatu.trim();
    }
}