package com.oyms.model;

import java.util.Date;

import org.springframework.stereotype.Component;

@Component
public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodName
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String goodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodtype
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String goodtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodprice
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Float goodprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodnum
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Long goodnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gooddesc
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String gooddesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodImgUrl
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String goodimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.isDelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Byte isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodName
     *
     * @return the value of goods.goodName
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodName
     *
     * @param goodname the value for goods.goodName
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodtype
     *
     * @return the value of goods.goodtype
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getGoodtype() {
        return goodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodtype
     *
     * @param goodtype the value for goods.goodtype
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodtype(String goodtype) {
        this.goodtype = goodtype == null ? null : goodtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodprice
     *
     * @return the value of goods.goodprice
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Float getGoodprice() {
        return goodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodprice
     *
     * @param goodprice the value for goods.goodprice
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodprice(Float goodprice) {
        this.goodprice = goodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodnum
     *
     * @return the value of goods.goodnum
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Long getGoodnum() {
        return goodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodnum
     *
     * @param goodnum the value for goods.goodnum
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodnum(Long goodnum) {
        this.goodnum = goodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gooddesc
     *
     * @return the value of goods.gooddesc
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getGooddesc() {
        return gooddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gooddesc
     *
     * @param gooddesc the value for goods.gooddesc
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGooddesc(String gooddesc) {
        this.gooddesc = gooddesc == null ? null : gooddesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodImgUrl
     *
     * @return the value of goods.goodImgUrl
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getGoodimgurl() {
        return goodimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodImgUrl
     *
     * @param goodimgurl the value for goods.goodImgUrl
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodimgurl(String goodimgurl) {
        this.goodimgurl = goodimgurl == null ? null : goodimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.isDelete
     *
     * @return the value of goods.isDelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.isDelete
     *
     * @param isdelete the value for goods.isDelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}