package com.oyms.model;

import java.util.List;

import org.springframework.stereotype.Component;

@Component
public class ParentType {

	private Integer id;

	private String pname;

	private Byte isdelete;

	private List<GoodType> goodTypes;

	public List<GoodType> getGoodTypes() {
		return goodTypes;
	}

	public void setGoodTypes(List<GoodType> goodTypes) {
		this.goodTypes = goodTypes;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname == null ? null : pname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column parenttype.isdelete
	 *
	 * @return the value of parenttype.isdelete
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	public Byte getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column parenttype.isdelete
	 *
	 * @param isdelete the value for parenttype.isdelete
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	public void setIsdelete(Byte isdelete) {
		this.isdelete = isdelete;
	}
}