package com.oyms.mapper;

import com.oyms.model.AuditStatu;
import com.oyms.model.AuditStatuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AuditStatuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    long countByExample(AuditStatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int deleteByExample(AuditStatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int insert(AuditStatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int insertSelective(AuditStatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    List<AuditStatu> selectByExampleWithRowbounds(AuditStatuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    List<AuditStatu> selectByExample(AuditStatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    AuditStatu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") AuditStatu record, @Param("example") AuditStatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int updateByExample(@Param("record") AuditStatu record, @Param("example") AuditStatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int updateByPrimaryKeySelective(AuditStatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditstatus
     *
     * @mbg.generated Sun Nov 03 23:48:19 CST 2019
     */
    int updateByPrimaryKey(AuditStatu record);
}