package com.oyms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.oyms.model.Goods;
import com.oyms.model.GoodsExample;

public interface GoodsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	long countByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int deleteByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	List<Goods> selectByExampleWithRowbounds(GoodsExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	List<Goods> selectByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	Goods selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goods
	 *
	 * @mbg.generated Mon Oct 28 16:48:09 CST 2019
	 */
	int updateByPrimaryKey(Goods record);


}