package com.oyms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.oyms.model.GoodType;
import com.oyms.model.GoodTypeExample;

public interface GoodTypeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	long countByExample(GoodTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int deleteByExample(GoodTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int insert(GoodType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int insertSelective(GoodType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	List<GoodType> selectByExampleWithRowbounds(GoodTypeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	List<GoodType> selectByExample(GoodTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	GoodType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int updateByExampleSelective(@Param("record") GoodType record, @Param("example") GoodTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int updateByExample(@Param("record") GoodType record, @Param("example") GoodTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int updateByPrimaryKeySelective(GoodType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table goodtype
	 *
	 * @mbg.generated Tue Oct 29 20:45:56 CST 2019
	 */
	int updateByPrimaryKey(GoodType record);

}